spring.thymeleaf.prefix: classpath:/template/
spring.thymeleaf.suffix: .html
spring.thymeleaf.mode: LEGACYHTML5
spring.thymeleaf.cache: false

security.basic.enabled: false

# OpenIoT 配置
bupt.thingsboard:
  host: 10.108.217.227
  port: 8080