spring.thymeleaf.prefix: classpath:/template/
spring.thymeleaf.suffix: .html
spring.thymeleaf.mode: LEGACYHTML5
spring.thymeleaf.cache: false

security.basic.enabled: false

# OpenIoT 配置
bupt.thingsboard:
  host: 10.108.219.8
  port: 8080
  login_url: http://10.108.219.8:8080/api/auth/login